### ISSUE TITLE
Get pins from a board

### ISSUE THREAD

**Issue by jonathanpardon** [hansott/pinterest-php#15]
There seems to be no function available to get the pins from a certain board (of the authenticated user).
Would be nice to have this!
Thanks

**Comment by turanct** [comment]
@hansott 

it should be something like 

``` php
    /**
     * Get pins of a board
     *
     * @return Response
     */
    public function getBoardPins($boardId)
    {
        $request = new Request('GET', sprintf('boards/%s/pins/', $boardId));

        return $this->fetchMultiplePins($request);
    }
```

**Comment by hansott** [comment]
Thanks for your issue report! I've added the proposed method by @turanct (Thanks!).

See https://github.com/hansott/pinterest-php#get-the-pins-of-a-board for docs. :rocket:
