### ISSUE TITLE
Long board id like 641763084339350760 causing issue

### ISSUE THREAD

**Issue by shailesh-daund** [hansott/pinterest-php#18]
The current pinterest id like 641763084339350760.
If we call create pin method it will not able to create pin on given board id.
This issue is due to the typecasting.

**Comment by shailesh-daund** [comment]
The fixes for this issue is added in this [pull request](https://github.com/hansott/pinterest-php/pull/19).

**Comment by yogeshbonzer** [comment]
So need to removed typecasting for boardId from src/Pinterest/Api.php line no. 454 (CreatePin() function)

**Comment by hansott** [comment]
Closed by https://github.com/hansott/pinterest-php/pull/19

**Comment by hansott** [comment]
A new release was tagged: https://github.com/hansott/pinterest-php/releases/tag/3.0.1
