### ISSUE TITLE
Notice: Undefined offset: 1 in /vendor/hansott/pinterest-php/src/Pinterest/Http/BuzzClient.php on line 71

### ISSUE THREAD

**Issue by SuriyaPrakashWebDev** [hansott/pinterest-php#20]
Hi,
  I have installed the PHP Pinterest API on my server and I have authenticated the user using OAuth. When I am trying to get board details I am facing an issue "Notice: Undefined offset: 1 in /vendor/hansott/pinterest-php/src/Pinterest/Http/BuzzClient.php on line 71". I have debugged the issue and found that the key "Pinterest-Generated-By" doesn't have the value. For this please refer Line number 71 in /vendor/hansott/pinterest-php/src/Pinterest/Http/BuzzClient.php
  
  Line cauisng issue,

  list($key, $value) = explode(': ', $header);
  
  My code:  

	$client = new Pinterest\Http\BuzzClient();

	$auth = Pinterest\Authentication::onlyAccessToken($client, $token);
	$api = new Pinterest\Api($auth);

	$response = $api->getUserBoards();

Please let me know why I am facing this issue. And do I need to add value in settings to get the value for "Pinterest-Generated-By"?
	
Thanks

**Comment by PavithraHari** [comment]
Hi,
I am also facing the same issue 
I have installed the PHP Pinterest API on my server and I have authenticated the user using OAuth. When I am trying to get board details I am facing an issue "Notice: Undefined offset: 1 in /vendor/hansott/pinterest-php/src/Pinterest/Http/BuzzClient.php on line 71". I have debugged the issue and found that the key "Pinterest-Generated-By" doesn't have the value. For this please refer Line number 71 in /vendor/hansott/pinterest-php/src/Pinterest/Http/BuzzClient.php

Line cauisng issue,

list($key, $value) = explode(': ', $header);

My code:

$client = new Pinterest\Http\BuzzClient();

$auth = Pinterest\Authentication::onlyAccessToken($client, $token);
$api = new Pinterest\Api($auth);

$response = $api->getUserBoards();
Please let me know why I am facing this issue. And do I need to add value in settings to get the value for "Pinterest-Generated-By"?

Thanks

**Comment by PavithraHari** [comment]
Hi,
I am also facing the same issue
I have installed the PHP Pinterest API on my server and I have authenticated the user using OAuth. When I am trying to get board details I am facing an issue "Notice: Undefined offset: 1 in /vendor/hansott/pinterest-php/src/Pinterest/Http/BuzzClient.php on line 71". I have debugged the issue and found that the key "Pinterest-Generated-By" doesn't have the value. For this please refer Line number 71 in /vendor/hansott/pinterest-php/src/Pinterest/Http/BuzzClient.php

Line cauisng issue,

list($key, $value) = explode(': ', $header);

My code:

$client = new Pinterest\Http\BuzzClient();

$auth = Pinterest\Authentication::onlyAccessToken($client, $token);
$api = new Pinterest\Api($auth);

$response = $api->getUserBoards();
Please let me know why I am facing this issue. And do I need to add value in settings to get the value for "Pinterest-Generated-By"?

Thanks

**Comment by hansott** [comment]
Thanks for reporting. I'll take a look!

**Comment by PavithraHari** [comment]
Hi,
   Have you check this error,
Notice: Undefined offset: 1 in /vendor/hansott/pinterest-php/src/Pinterest/Http/BuzzClient.php on line 71 

Can you let us know why the issue is occurring. We have also shared our code what we used for the development.

Thanks

**Comment by hansott** [comment]
Just pushed a fix and I'm waiting for the test suite to run. Once that's completed I'll tag a new version.

**Comment by hansott** [comment]
I've tagged a new version: https://github.com/hansott/pinterest-php/releases/tag/3.0.2

Run `$ composer update` to get the latest version. Have fun!

**Comment by PavithraHari** [comment]
Thank you for supporting we will Update new version

**Comment by SuriyaPrakashWebDev** [comment]
Thanks @hansott the new version worked 👍
