### ISSUE TITLE
Need Suggesstion on Pinterest API options

### ISSUE THREAD

**Issue by PavithraHari** [hansott/pinterest-php#22]
Hi,
    We are using the Pinterest API to add pins in our Boards. We have figured out the steps in PHP to get access token and create pins in our board. On proceeding further with our development we have few doubts, 
 
 1. We came across a option called "Section" in each board. We have researched to find the PHP code for creating the section in a board. But we can't able to get any reference for creating sections in a board. So can anyone help us by providing any reference to create sections.
 
 2. We tried to try the advertisement in Pinterest Campaign, but in Step #3 it is allowing us to select only one pin at a time for campaign promotion. I tried with different types of promotions but I can't able to select multiple pins at a time for promotion. Can we able to select multiple pins in the ads manager? Or is there any API to manager the ads and the campaigns, so we can control it through automation. Please let us know your suggestions.
  
Thanks

**Comment by hansott** [comment]
I don't see any API endpoints to deal with ads... If you have a link, feel free to share and I'll have a look.

You can contact Pinterest [here](https://developers.pinterest.com/support/contact/) if you need more information.

Note that I just maintain an API wrapper, I don't offer support on the Pinterest API. I hope you understand that.
