### ISSUE TITLE
Edit Pins option is missing

### ISSUE THREAD

**Issue by SuriyaPrakashWebDev** [hansott/pinterest-php#23]
Hi,
   I am using this API for managing boards and pins of Pinterest. In this API, I can't able to find the function for "Edit Pins". Can you please add the function and release the new file as soon as possible.

And do you have any reference to managing the Pinterest Campaigns and Ads through API?

Waiting for your response.

Thanks

**Comment by hansott** [comment]
Hey there, sorry for the delayed answer, I will happily accept a pull request that adds the required behaviour, if not, I'll try doing it within this week, no promises though. 

As for the Ads, it's not supported in their API, it's not possible with this package. Feel free to contact Pinterest here: https://developers.pinterest.com/support/contact/

**Comment by SuriyaPrakashWebDev** [comment]
Thanks for the response, reply me here once you added the Edit functionality. It would be helpful.

**Comment by hansott** [comment]
It's available in version 3.1.0. Have fun!
