### ISSUE TITLE
Cannot Authorize Token from Code

### ISSUE THREAD

**Issue by flameblue59** [hansott/pinterest-php#24]
Hi, I have a problem when authorizing my code to token. I have tried the javascript version and it works fine but I need to do with PHP. Here is the code.

```
$client = new Pinterest\Http\BuzzClient();
$clientId = "xxx";
$clientSecret = "xxx";
$auth = new Pinterest\Authentication($client, $clientId, $clientSecret);

if(empty($_GET["code"])){
	$callbackurl = 'mycallbackurl';
	$url = $auth->getAuthenticationUrl(
		$callbackurl,
		array(
			Scope::READ_PUBLIC,
			Scope::WRITE_PUBLIC,
			Scope::READ_RELATIONSHIPS,
			Scope::WRITE_RELATIONSHIPS,
		),
		'random-string'
	);

	header('Location: ' . $url);
	exit;
}
else{
	$code = $_GET['code'];
	$token = $auth->requestAccessToken($code);
	echo $token; --> here is the error
}
```

It produces code but the problem is when the code is converted into a token. That gave this following error.

`Fatal error: Uncaught Pinterest\Api\Exceptions\TokenMissing in /home/admin/ocicio/botsector/vendor/hansott/pinterest-php/src/Pinterest/Authentication.php:222 Stack trace: #0 /home/admin/ocicio/botsector/index.php(31): Pinterest\Authentication->requestAccessToken('d77eecdc2dae2ad...') #1 {main} thrown in /home/admin/ocicio/botsector/vendor/hansott/pinterest-php/src/Pinterest/Authentication.php on line 222`

**Comment by hansott** [comment]
Hi!

I just tested the latest version and it's working perfectly for me.

I don't think it's a problem with the package because of the other issue you opened: https://github.com/dirkgroenen/Pinterest-API-PHP/issues/80.

* Maybe your IP address is blocked? Read more in https://github.com/hansott/pinterest-php/issues/16. You might want to try using a different IP address. Does it work locally?
* Do you see the authorize dialog correctly when visiting the redirection URL?
* Maybe try dumping of `$response = $this->http->execute($request);` in `requestAccessToken`?

I'll be glad to help if it's an issue with this package. Otherwise it might be better to contact Pinterest: https://developers.pinterest.com/support/contact

Hans

**Comment by flameblue59** [comment]
Could you please to share the raw code that you have, I am trying to follow it but it does not work. However, it works when I try to use javascript method.

Anyway, my IP certainly not getting blocked and the authorized dialog is shown. Anyway how about dumping it? I am trying to put the code before requestAccessToken but it does not work.

**Comment by hansott** [comment]
This piece of code should work fine:

```php
<?php

require_once 'vendor/autoload.php';

date_default_timezone_set('UTC');

use Pinterest\App\Scope;

$client = new \Pinterest\Http\BuzzClient();
$appId = 'myAppId';
$appSecret = 'myAppSecret';
$auth = new \Pinterest\Authentication($client, $appId, $appSecret);

$url = $auth->getAuthenticationUrl(
    'https://localhost',
    array(
        Scope::READ_PUBLIC,
        Scope::WRITE_PUBLIC,
        Scope::READ_RELATIONSHIPS,
        Scope::WRITE_RELATIONSHIPS,
    ),
    'random-state'
);

/**
 * 1. Redirect to $url, when the user is redirect back, grab the code from the query string
 * 2. Get the access token with: $auth->requestAccessToken('code');
 * 3. Use client with access token: $auth = \Pinterest\Authentication::onlyAccessToken(
 *       $client,
 *       'accessToken'
 *    );
 *
 * $api = new \Pinterest\Api($auth);
 * $response = $api->getUserFollowers();
 * var_dump($response);
 */
```

It's IP address of your server that is important. The one that trades the code for an access token (where your PHP code is running).

The authorized dialog will always be shown if correct client_id / redirect_uri provided. (It's just an HTTP redirect, so not possible to be blocked)

**Comment by flameblue59** [comment]
Hi, I have applied the code above. However, it still produce the same error. Would you please to check it here https://ocicio.com/botsector/. It does not work when I convert token from $_GET['code'] which generated from Pinterest itself.

```
<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
require_once 'vendor/autoload.php';

date_default_timezone_set('UTC');

use Pinterest\App\Scope;

$client = new \Pinterest\Http\BuzzClient();
$appId = 'xxx';
$appSecret = 'xxx';
$auth = new \Pinterest\Authentication($client, $appId, $appSecret);

$url = $auth->getAuthenticationUrl(
    'https://ocicio.com/botsector/',
    array(
        Scope::READ_PUBLIC,
        Scope::WRITE_PUBLIC,
        Scope::READ_RELATIONSHIPS,
        Scope::WRITE_RELATIONSHIPS,
    ),
    'random-state'
);

if(!ISSET($_GET['code'])){
	header('Location: '.$url);
	exit();
}
else{
	echo $_GET['code'];
	echo $auth->requestAccessToken($_GET['code']);
}
/**
 * 1. echo $url;
 * 2. echo $auth->requestAccessToken('code');
 * 3. $auth = \Pinterest\Authentication::onlyAccessToken(
 *       $client,
 *       'accessToken'
 *    );
 *
 * $api = new \Pinterest\Api($auth);
 * $response = $api->getUserFollowers();
 * var_dump($response);
 */
```

**Comment by hansott** [comment]
Can you `var_dump` the result of 

```php
$response = $this->http->execute($request);
```

in `Authentication->requestAccessToken`?

**Comment by flameblue59** [comment]
Anyway, I just want to make sure, is this code correct?

```
$response = $auth->http->execute($auth->requestAccessToken($_GET['code']));
var_dump($response);
```
By doing this, I get this following error.

> Fatal error: Cannot access private property Pinterest\Authentication::$http in /home/admin/ocicio/botsector/index.php on line 33

**Comment by hansott** [comment]
If you go to `path/to/composer/vendor/hansott/pinterest-php/src/Pinterest/Authentication.php` you can find the declaration of `requestAccessToken`, in `requestAccessToken` you need to add `var_dump($response)`...

**Comment by turanct** [comment]
@flameblue59 you wrote here https://github.com/hansott/pinterest-php/issues/24#issuecomment-376185613 that you're doing 

```php
$response = $auth->http->execute($auth->requestAccessToken($_GET['code']));
var_dump($response);
```

but you should be doing 

```php
$response = $auth->requestAccessToken($_GET['code']);
var_dump($response);
```
instead

**Comment by flameblue59** [comment]
@hansott 
Done, here is the result

> 7aa15d50d7c3bc67object(Pinterest\Http\Response)#10 (6) { ["body"]=> object(stdClass)#11 (2) { ["status"]=> int(403) ["message"]=> string(9) "Forbidden" } ["statusCode":"Pinterest\Http\Response":private]=> int(403) ["rawBody":"Pinterest\Http\Response":private]=> string(41) "{ "status": 403, "message": "Forbidden" }" ["headers":"Pinterest\Http\Response":private]=> array(8) { ["Age"]=> string(1) "0" ["Cache-Control"]=> string(7) "private" ["Content-Type"]=> string(37) "application/javascript; charset=utf-8" ["X-Pinterest-RID"]=> string(12) "467067484024" ["Content-Length"]=> string(2) "41" ["Date"]=> string(29) "Mon, 26 Mar 2018 14:33:57 GMT" ["Connection"]=> string(10) "keep-alive" ["Pinterest-Generated-By:"]=> string(0) "" } ["result":"Pinterest\Http\Response":private]=> NULL ["request":"Pinterest\Http\Response":private]=> object(Pinterest\Http\Request)#7 (4) { ["method":"Pinterest\Http\Request":private]=> string(4) "POST" ["endpoint":"Pinterest\Http\Request":private]=> string(40) "https://api.pinterest.com/v1/oauth/token" ["params":"Pinterest\Http\Request":private]=> array(4) { ["grant_type"]=> string(18) "authorization_code" ["client_id"]=> string(19) "XXX" ["client_secret"]=> string(64) "XXX" ["code"]=> string(16) "7aa15d50d7c3bc67" } ["headers":"Pinterest\Http\Request":private]=> array(0) { } } }

**Comment by flameblue59** [comment]
@turanct 
thank you for your help.

**Comment by hansott** [comment]
Thanks for doing that. I've removed the client_id / client_secret from your comment.

The 403 Forbidden is proof that your IP address of your server is blocked, it's the same as #16... Try it locally (on your own computer, using a localhost redirect URI like in the example).

You can always contact Pinterest to request an unblock: https://developers.pinterest.com/support/contact

Otherwise you'll need a different IP address.

Good luck!

Hans
