### ISSUE TITLE
Simple Question regarding "Follow a Board" and "Repin / Save a Pin" functions

### ISSUE THREAD

**Issue by narainsagar** [hansott/pinterest-php#26]
Hey,
Thanks for this library 👍 I did a bit of research and seems like this is the only Pinterest official API PHP wrapper which is being maintained regularly.. 👍 

I have 2 quick questions:

Does it support all API endpoints ? and specifically Does it have methods for following functions:

- Follow a Board
- Repin / Save A Pin

Thanks.

**Comment by hansott** [comment]
Hi! I try to keep the package up-to-date indeed. 😊

I think most endpoints are supported (Except unfollowing boards https://github.com/hansott/pinterest-php/issues/29 & users https://github.com/hansott/pinterest-php/issues/28). If there's an endpoint you need you can always submit a PR or open an improvement request. 

* Following a board isn't supported at this moment, I've created https://github.com/hansott/pinterest-php/issues/27 and I'll try tackling it as soon as possible 🚀.
* Saving a pin isn't possible with the API at this moment (as far as I know)... You can always create a new Pin with the content of the pin you want to save.

Hans

**Comment by narainsagar** [comment]
@hansott Alright, Thanks!

**Comment by hansott** [comment]
I've just tagged a new version: https://github.com/hansott/pinterest-php/releases/tag/3.2.0 😎

**Comment by narainsagar** [comment]
Hi @hansott I followed the docs from following sections:

https://github.com/hansott/pinterest-php#create-a-pin
https://github.com/hansott/pinterest-php#get-a-pin

and tried with your mentioned way for _repining a pin_ i.e.,

> Saving a pin isn't possible with the API at this moment (as far as I know)... You can always create a new Pin with the content of the pin you want to save.

Below is my sample code:
```
$pinId = $_REQUEST['pinId']; // original Pin ID to repin to.
$boardId = $_REQUEST['boardId']; // board ID

$client = new Pinterest\Http\BuzzClient();
$auth = Pinterest\Authentication::withAccessToken($client, CONSUMER_KEY, CONSUMER_SECRET, $token);
$api = new Pinterest\Api($auth);

$response = $api->getPin($pinId);

if (!$response->ok()) {
    return die($response->getError());
}

$original_pin_info = $response -> result();

$note = $original_pin_info -> note;
$optionalLink = 'http://hansott.github.io/'; // $original_pin_info -> link
// Load an image from a url.
$image_url = 'https://i.pinimg.com/564x/56/6b/11/566b118eb53f7349ef42aa768538b7f1.jpg';
// $image_url = $original_pin_info -> image -> original -> url;
$image = Pinterest\Image::file($image_url);

$response = $api->createPin($boardId, $note, $image, $optionalLink);

if (!$response->ok()) {
    return die($response->getError());
}

$success = true;
$data = $response->result();

// send response.
echo json_encode($data);
```

Seems like some issue at this line `$image = Pinterest\Image::file($image_url);`

OR maybe I'm missing something here ?

Here's error in response:
```
Warning: finfo::file(): Failed identify data 0:(null) in /Users/narainsagar/www/SweepWidgetLive/vendor/kriswallsmith/buzz/lib/Buzz/Message/Form/FormUpload.php on line 116
```
<img width="1043" alt="screen shot 2018-04-13 at 3 42 09 am" src="https://user-images.githubusercontent.com/13800762/38707855-b0592a22-3ecc-11e8-809b-eb618698940b.png">

Can anyone look into this / share their thoughts on this. Thanks.

**Comment by hansott** [comment]
Try using

```php
$image = Pinterest\Image::url('http://lorempixel.com/g/400/200/cats/');
```

(instead of `Pinterest\Image::file`)
