### ISSUE TITLE
deletePin sprintf format causes data conversion and thus results in pin not found

### ISSUE THREAD

**Issue by mschroebel** [hansott/pinterest-php#31]
deletePin->658440407994591131
print_r($request):
Pinterest\Http\Request Object
(
    [method:Pinterest\Http\Request:private] => DELETE
    [endpoint:Pinterest\Http\Request:private] => pins/2147483647/
    [params:Pinterest\Http\Request:private] => Array
        (
        )

    [headers:Pinterest\Http\Request:private] => Array
        (
        )

)

My fix:
Api.php Line 489
< $request = new Request('DELETE', sprintf('pins/%d/', $pinId));

> $request = new Request('DELETE', sprintf('pins/%s/', $pinId));

**Comment by turanct** [comment]
Looks like an integer overflow to me, could be fixed by assuming the pin id is a string instead of an int indeed.

**Comment by mschroebel** [comment]
You know their making that look like a number is a gotcha waiting to happen.  If you look at the spec it says the id is a string. I wasn't thinking of that when I stumbled on this and posted the issue. I had made the ids varchar in my database when I created it yesterday. Spec:
https://developers.pinterest.com/docs/api/pins/

**Comment by hansott** [comment]
I'll take a look!

**Comment by hansott** [comment]
I've just released a new version: https://github.com/hansott/pinterest-php/releases/tag/3.2.1 📌
