### ISSUE TITLE
Error - Operation timed out after 5000 milliseconds with 0 bytes received

### ISSUE THREAD

**Issue by narainsagar** [hansott/pinterest-php#33]
I am not sure, if there's any issue or something but I noticed and got this this error once (*I'm using the api from past 15+ days, i.e., I never noticed this before.).

`Fatal error: Uncaught Exception: Operation timed out after 5000 milliseconds with 0 bytes received in /Users/narainsagar/www/SweepWidgetLive/vendor/hansott/pinterest-php/src/Pinterest/Http/BuzzClient.php on line 123
--`

<img width="803" alt="screen shot 2018-04-13 at 4 19 52 am" src="https://user-images.githubusercontent.com/13800762/38708966-19ba5a5e-3ed2-11e8-9ccd-dc3dbf519ad5.png">

**Comment by hansott** [comment]
Temporarily hiccup?

**Comment by narainsagar** [comment]
No idea 😄 Didn't notice the error again 😐 thanks
