### ISSUE TITLE
Can not install package

### ISSUE THREAD

**Issue by yurik3zzz** [hansott/pinterest-php#36]
Failed to download hansott/pinterest-php from dist: The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems): ZipArchive::extractTo(): Full extraction path exceed MAXPATHLEN (260)
    Now trying to download from source

System: Win10
some files are very long name

pinterest-php-master\tests\Pinterest\responses\post_v1_pins_314196580192658592_A_note!_7839fe8158191d9aedc41da6132fff1a_id_link_url_creator_board_created_at_note_color_counts_media_attribution_image_metadata.json

**Comment by hansott** [comment]
I'll check tonight for a solution. Maybe I can use an md5 for replacing the arguments. 🤔

**Comment by Icesik** [comment]
Hi,

Here is what I've got when I run composer update with fresh requirement for your package :

`  - Installing hansott/pinterest-php (3.2.0): Downloading (100%)
    Failed to download hansott/pinterest-php from dist: Could not delete /mnt/hgfs/Shared/dinerscope/vendor/hansott/pinterest-php:
    Now trying to download from source
  - Installing hansott/pinterest-php (3.2.0): Cloning 9c50073458
    9c500734584153561a48782b974acb525768f88a is gone (history was rewritten?)


  [RuntimeException]
  Failed to execute git checkout '9c500734584153561a48782b974acb525768f88a' -- && git reset --hard '9c500734584153561a48782b974acb525768f88a' --
  HEAD is now at 9c50073... 📝 Document follow/unfollow methods
  error: unable to create file tests/Pinterest/responses/post_v1_pins_314196580192658592_A_note!_7839fe8158191d9aedc41da6132fff1a_id_link_url_creator_board_created_at_note_color_counts_media_attribution_image_metadata.json: File name too long
  error: unable to create file tests/Pinterest/responses/post_v1_pins_314196580192658592_Test_pin_base64_12b92a1f5683b3a302e0bd5dd3f9b180_id_link_url_creator_board_created_at_note_color_counts_media_attribution_image_metadata.json:
  File name too long
  error: unable to create file tests/Pinterest/responses/post_v1_pins_314196580192658592_Test_pin_file_1bd848b1381d24d4d778c490c877bc20_id_link_url_creator_board_created_at_note_color_counts_media_attribution_image_metadata.json: File name too long
  error: unable to create file tests/Pinterest/responses/post_v1_pins_314196580192658592_Test_pin_url_7839fe8158191d9aedc41da6132fff1a_id_link_url_creator_board_created_at_note_color_counts_media_attribution_image_metadata.json: File name too long
  fatal: Could not reset index file to revision '9c500734584153561a48782b974acb525768f88a'.`

System : Ubuntu server 17.04

Thanks in advance!

**Comment by hansott** [comment]
Just tagged a new version: https://github.com/hansott/pinterest-php/releases/tag/3.2.2

Can you check if you're able to install? Thanks!
