### ISSUE TITLE
Fatal error: Uncaught Pinterest\Http\Exceptions\RateLimitedReached: Rate limit reached. in 

### ISSUE THREAD

**Issue by narainsagar** [hansott/pinterest-php#38]
Getting this error 😐 
<img width="672" alt="screen shot 2018-04-27 at 12 19 03 pm" src="https://user-images.githubusercontent.com/13800762/39349671-37ca22a6-4a15-11e8-85ee-150212f3c7b5.png">

**Comment by hansott** [comment]
Hi there, not much I can do about that. It's not an issue with this package.

See https://developers.pinterest.com/docs/api/overview/#rate-limiting

> Effective April 16 2018, all unapproved apps are allowed 10 calls per hour for each unique user token.

> After you successfully submit an app for approval, each app (with a unique app ID) is allowed 1000 calls per hour for each unique user token.

**Comment by narainsagar** [comment]
@hansott Oh, Ok thanks for sharing this.
