### ISSUE TITLE
I can't get user info

### ISSUE THREAD

**Issue by pauznet** [hansott/pinterest-php#40]
Hello, im new here and i like start use this API
here is my code (one file send.php):

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
require __DIR__ . '/vendor/autoload.php';

use Pinterest\App\Scope;

$client = new \Pinterest\Http\BuzzClient();
$appId = '.............';
$appSecret = '...............................';
$auth = new \Pinterest\Authentication($client, $appId, $appSecret);

$url = $auth->getAuthenticationUrl(
    'https://www.mysite.com/hansott/send.php',
    array(
        Scope::READ_PUBLIC,
        Scope::WRITE_PUBLIC,
        Scope::READ_RELATIONSHIPS,
        Scope::WRITE_RELATIONSHIPS,
    ),
    'random-state'
);

if(!ISSET($_GET['code'])){
    header('Location: '.$url);
    exit();
}
else{
    $token = $auth->requestAccessToken($_GET['code']);
    $auth = Pinterest\Authentication::onlyAccessToken($client, $token);
    $api = new Pinterest\Api($auth);

    $response = $api->getCurrentUser();

    if (!$response->ok()) {
        die($response->getError());
    }

    $user = $response->result(); // $user instanceof Objects\User

    var_dump($user);
}

Thanks you

**Comment by hansott** [comment]
Hi @pauznet, in order to help you, I need a bit more information. Do you get an error, exception or something else?

**Comment by hansott** [comment]
Closing due inactivity... Feel free to open again with debug information.
