### ISSUE TITLE
Save (Re-Pin) a pin

### ISSUE THREAD

**Issue by hdsouza** [hansott/pinterest-php#42]
Hans, Thanks for the code.
Do you have the ability to Save (Re-Pin) a pin.
(I am not referring to Create a pin, which i see you can already do)

Thanks
Hil

**Comment by hansott** [comment]
I've asked this before, sadly the API doesn't support that (which is odd, right?):

<img width="600" alt="Screenshot 2019-08-29 17 26 49" src="https://user-images.githubusercontent.com/3886384/63954102-d8995f00-ca82-11e9-9d20-04eeea60b8da.png">

If it's not possible with the official API then this package will not support it either.

Cheers!

**Comment by hdsouza** [comment]
Ahh . Thanks for investigating this Hans
