### ISSUE TITLE
$api->getUserBoards() suddenly failing

### ISSUE THREAD

**Issue by emerika** [hansott/pinterest-php#43]
This happens after I auth a new user. All of which works fine. The user has 2 boards. 

basically I do this:

$response = $api->getUserBoards();
if (!$response->ok()) 
      {"message": "Invalid parameters.", "type": "api", "param": "creator"}

Any thoughts?

**Comment by hansott** [comment]
Hey @emerika, I'll check asap when I have time. Thanks for understanding!

**Comment by emerika** [comment]
no problem -- I made a fix to keep our site up. Removing 'creator' from the array is enough to fix this. I wanted to make the smallest change possible.

    private function fetchMultipleBoards(Request $request, array $fields = null)
    {
        $fields = $fields ? $fields : Board::fields();
        array_splice($fields, 4, 1); // the change
        $request->setFields($fields);

        return $this->execute($request, function (Response $response) {
            $mapper = new Mapper(new Board());

            return $mapper->toList($response);
        });
    }

**Comment by hansott** [comment]
Hey @emerika, I found the cause:

![Screenshot 2019-10-29 20 26 20](https://user-images.githubusercontent.com/3886384/67801877-69dc8000-fa8a-11e9-8ddc-4c0c3e736dfb.png)

It seems that Pinterest has deprecated the `creator` field... Would you like to contribute a fix by removing https://github.com/hansott/pinterest-php/blob/master/src/Pinterest/Objects/Board.php#L35 and https://github.com/hansott/pinterest-php/blob/master/src/Pinterest/Objects/Board.php#L76? I'm quite busy at this moment and it might take a while before I'm able to fix this.... If you're up for it, send a PR and I'll review it ASAP! 😇

**Comment by hansott** [comment]
And thanks for reporting this issue.
