### ISSUE TITLE
ACCESS_TOKEN Pin Sharing

### ISSUE THREAD

**Issue by seckinkocak** [hansott/pinterest-php#50]
Hello there,

I do not have API access, can we pin only with access_token? Can you share sample code.

**Comment by hansott** [comment]
You can create a pin using https://github.com/hansott/pinterest-php#create-a-pin

note: there's currently no way to repin something using v1 of the API (afaik)
note: there's a new version of the API on its way, I don't know what functionality is supported

**Comment by hansott** [comment]
(https://github.com/dirkgroenen/pinterest-api-php/issues/119)

It's not really useful to post questions like this, be specific about what you want to achieve. We maintain these projects without getting payed for it. It would be great if you can do some more research yourself, thanks! If you have any specific questions related to this package, I'm happy to help.
