### ISSUE TITLE
Parameter 'board' is required.

### ISSUE THREAD

**Issue by evrenonur** [hansott/pinterest-php#52]
$image = Pinterest\Image::file('images.jpg');
$response = $api->createPin('746612513164716763', "test func", $image, "https://website.com");

if (!$response->ok()) {
    die($response->getError());
}

failed: Parameter 'board' is required.

**Comment by hansott** [comment]
Hey @evrenonur 👋 

When I look at the code, I don't see how `board` could be missing... I have limited time to maintain this package (See #51).

Can you check what `$request` looks like here (when you call `createPin`)? https://github.com/hansott/pinterest-php/blob/master/src/Pinterest/Api.php#L78 (`var_dump` or whatever)

Be careful with your access token! ;)

**Comment by evrenonur** [comment]
> Hey @evrenonur 👋
> 
> When I look at the code, I don't see how `board` could be missing... I have limited time to maintain this package (See #51).
> 
> Can you check what `$request` looks like here (when you call `createPin`)? https://github.com/hansott/pinterest-php/blob/master/src/Pinterest/Api.php#L78 (`var_dump` or whatever)
> 
> Be careful with your access token! ;)

`

object(Pinterest\Http\Response)#15 (6) {
--
  | ["body"]=>
  | NULL
  | ["statusCode":"Pinterest\Http\Response":private]=>
  | int(400)
  | ["rawBody":"Pinterest\Http\Response":private]=>
  | string(73) "{"type":"api","message":"Parameter 'board' is required.","param":"board"}"
  | ["headers":"Pinterest\Http\Response":private]=>
  | array(17) {
  | ["Content-Type"]=>
  | string(16) "application/json"
  | ["Content-Length"]=>
  | string(2) "73"
  | ["pinterest-version"]=>
  | string(7) "b4253a7"
  | ["x-content-type-options"]=>
  | string(7) "nosniff"
  | ["x-frame-options"]=>
  | string(4) "DENY"
  | ["Access-Control-Allow-Origin"]=>
  | string(1) "*"
  | ["X-RateLimit-Remaining"]=>
  | string(2) "89"
  | ["X-RateLimit-Limit"]=>
  | string(3) "100"
  | ["pinterest-generated-by"]=>
  | string(27) "coreapp-ngapi-prod-0a01cc94"
  | ["x-envoy-upstream-service-time"]=>
  | string(2) "35"
  | ["Cache-Control"]=>
  | string(7) "private"
  | ["x-pinterest-rid"]=>
  | string(16) "1980019078858176"
  | ["Date"]=>
  | string(29) "Tue, 18 Aug 2020 10:34:09 GMT"
  | ["Connection"]=>
  | string(5) "close"
  | ["Set-Cookie"]=>
  | string(45) "_ir=0; Max-Age=1800; HttpOnly; Path=/; Secure"
  | ["X-CDN"]=>
  | string(6) "akamai"
  | ["Age"]=>
  | string(1) "0"
  | }
  | ["result":"Pinterest\Http\Response":private]=>
  | NULL
  | ["request":"Pinterest\Http\Response":private]=>
  | object(Pinterest\Http\Request)#11 (4) {
  | ["method":"Pinterest\Http\Request":private]=>
  | string(4) "POST"
  | ["endpoint":"Pinterest\Http\Request":private]=>
  | string(34) "https://api.pinterest.com/v1/pins/"
  | ["params":"Pinterest\Http\Request":private]=>
  | array(4) {
  | ["board"]=>
  | string(18) "856317385337685860"
  | ["note"]=>
  | string(9) "test func"
  | ["image"]=>
  | object(Pinterest\Image)#8 (2) {
  | ["type":"Pinterest\Image":private]=>
  | string(4) "file"
  | ["data":"Pinterest\Image":private]=>
  | string(10) "images.jpg"
  | }
  | ["fields"]=>
  | string(79) "id,link,url,board,created_at,note,color,counts,media,attribution,image,metadata"
  | }
  | ["headers":"Pinterest\Http\Request":private]=>
  | array(1) {
  | ["Authorization"]=>
  | string(83) "BEARER As4P5qFrLRFJMCVX8Qn60bXvpuquFiroG9GLSI5Che2B-qAERQviQDAAA-iCRv63RxugvSUAAAAA"
  | }
  | }
  | }

`

**Comment by hansott** [comment]
Deleted your comment because it contained your access token, from the docs: https://developers.pinterest.com/docs/api/pins/

> board (required): The board you want the new Pin to be on. In the format <username>/<board_name>.

You can't specify an ID of the board, will update the README (bbc809b75b58468702bd437d6405dea160825d20)
